---
title: "TP3"
author: "Israa BEN SASSI"
date: "9/27/2021"
output: html_document
---


# Partie 1 

## Question 2
 Simulation de 2000 réalisationd'une varaible aléatoire Z
```{r}
n = 2000
u = runif(n)
x = rnorm(n)
Z = (u < 3/5) * (x-1) + (u> 3/5) * (x+2)

```

```{r}
f = function(x){
         f = 3 * dnorm(x,-1,1) / 5 + 2 * dnorm(x,2,1) / 5
}

```

```{r}
t= seq(from = -5, to = 6, by = 0.1)
```


## Les valeurs estimer par Rozenblatt
```{r}

par(mfrow = c(2,2))
S = c(50,100,500,2000)
for (n in S){
  plot(t,f(t), type = "l",main= n)
  est1 = density(Z[1:n],kernel="rectangular",n=length(t), from=-5, to=6)
  est2 = density(Z[1:n],kernel="gaussian",n=length(t), from=-5, to=6)
  lines(est1, col = "cyan")
  lines(est2, col = "red")
  legend("topright", ,legend=c("Densite","est1","est2"),col=c("black","red","cyan"),lty=1)
}

par(new = TRUE)
```

```{r}
n1 = 1000
u1 = runif(n)
x1 = rnorm(n)
Z1 = (u1 < 3/5) * (x1-1) + (u1> 3/5) * (x1+2)
f = function(x1){
         f = 3 * dnorm(x1,-1,1) / 5 + 2 * dnorm(x1,2,1) / 5
}

k = seq(from = -5, to = 6, by = 0.1)

sZ = sd(Z1)
alpha = c(0.07,0.2,0.3,0.4,0.5,0.7,0.8)

par(mfrow = c(2,2))

S1 = c(50,100,200,1000)


for(a in alpha){
  fenetre = sZ*n1**(-a)
  for (n in S1){
  plot(k,f(k), type = "l", main= a, sub=n)
  PR= density(Z1[1:n],kernel="gaussian", bw = fenetre )
  lines(PR, col = "cyan")
  legend("topright", ,legend=c("Densite","PR"),col=c("black","cyan"),lty=1)
  }
}
par(new = TRUE)

```



# Partie 2 :
```{r}
nomfile = "http://lmi2.insa-rouen.fr/~bportier/Data/donpol.txt"
pollution <- read.table(file=nomfile,header=T,dec=".")
par(mfrow=c(1,3))


a = 0.2
colalpha = c("pink","purple","grey")
p = data.frame(pollution$ozon, pollution$temp, pollution$vent) 
names = c("Ozon","Temp", "Vent")
color = c("red","green","black")
kernel = c("gaussian", "epanechnikov", "rectangular","triangular", "biweight", "cosine", "optcosine")
ecart = NULL
fenetre = NULL
for (k in kernel){
for (i in 1:ncol(p)){
  hist(p[,i],prob=T,nclass=20,main= paste(names[i],"noyeau =" ,k),col="cyan")
  ecart[i] = sd(p[,i])
  fenetre[i] =  ecart[i]*nrow(p[i])**(-a)
  est = density(p[,i], bw = fenetre[i], kernel = k)
  lines(est, col= colalpha[i],  lwd=2.5)
  legend("topright",legend= paste("alpha =" , a))
  }

}
```


```{r}
for (i in 1:ncol(p)){
print(shapiro.test(p[,i]))
}
```


```{r}
rm(list=ls())
nbech = 400
n = 500
nb.ech.normal.ncr = 0
nb.ech.normal.un = 0
nb.ech.normal.std5 = 0
nb.ech.normal.std10 = 0
for (i in 1:nbech){
  ncr = rnorm(n)
  test.ncr = shapiro.test(ncr)
  if (test.ncr$p.value<0.05)
    nb.ech.normal.ncr = nb.ech.normal.ncr + 1
  
  un = runif(n = n, min = -2, max = 2)
  test.un = shapiro.test(un)
  if (test.un$p.value<0.05)
    nb.ech.normal.un = nb.ech.normal.un + 1
  
  std5 = rt(n = n, df = 5)
  test.std5 = shapiro.test(std5)
  if (test.std5$p.value<0.05)
    nb.ech.normal.std5 = nb.ech.normal.std5 + 1
  
  std10 = rt(n = n, df = 10)
  test.std10 = shapiro.test(std10)
  if (test.std10$p.value<0.05)
    nb.ech.normal.std10 = nb.ech.normal.std10 + 1
}

p.ech.normal.ncr = nb.ech.normal.ncr / 400
p.ech.normal.un = nb.ech.normal.un / 400
p.ech.normal.std5 = nb.ech.normal.std5 / 400
p.ech.normal.std10 = nb.ech.normal.std10 / 400

p.ech.normal.ncr
p.ech.normal.un 
p.ech.normal.std5 
p.ech.normal.std10 

```


```{r}
rm(list=ls())
nbech = 400
n = 100
nb.ech.normal.ncr = 0
nb.ech.normal.un = 0
nb.ech.normal.std5 = 0
nb.ech.normal.std10 = 0

nb.ech.u1.ncr = 0
nb.ech.u1.un = 0
nb.ech.u1.std5 = 0
nb.ech.u1.std10 = 0

nb.ech.u2.ncr = 0
nb.ech.u2.un = 0
nb.ech.u2.std5 = 0
nb.ech.u2.std10 = 0

for (i in 1:nbech){
  
  
  ncr = rnorm(n)
  test.ncr.ncr = ks.test(ncr,"pnorm",mean=0,sd=1)
  test.ncr.u1 = ks.test(ncr,"punif",-1,1)
  test.ncr.u2 = ks.test(ncr,"punif",-2,2)
  if (test.ncr.ncr$p.value<0.05){
    nb.ech.normal.ncr = nb.ech.normal.ncr + 1
  }
  else if (test.ncr.u1$p.value<0.05){
    nb.ech.u1.ncr = nb.ech.u1.ncr + 1
  }
  else if(test.ncr.u2$p.value<0.05){
    nb.ech.u2.ncr = nb.ech.u2.ncr + 1
  }
  
  
  un = runif(n = n, min = -2, max = 2)
  test.un.ncr = ks.test(un,"pnorm",mean=0,sd=1)
  test.un.u1 = ks.test(un,"punif",-1,1)
  test.un.u2 = ks.test(un,"punif",-2,2)
  if (test.ncr.ncr$p.value<0.05){
    nb.ech.normal.un = nb.ech.normal.un + 1
  }
  else if (test.ncr.u1$p.value<0.05){
    nb.ech.u1.un = nb.ech.u1.un + 1
  }
  else if(test.ncr.u2$p.value<0.05){
    nb.ech.u2.un = nb.ech.u2.un + 1
  }
  
  std5 = rt(n = n, df = 5)
  test.std5.ncr = ks.test(std5,"pnorm",mean=0,sd=1)
  test.std5.u1 = ks.test(std5,"punif",-1,1)
  test.std5.u2 = ks.test(std5,"punif",-2,2)
  if (test.std5.ncr$p.value<0.05){
    nb.ech.normal.std5 = nb.ech.normal.std5 + 1
  }
  else if (test.std5.u1$p.value<0.05){
    nb.ech.u1.std5 = nb.ech.u1.std5 + 1
  }
  else if(test.std5.u2$p.value<0.05){
    nb.ech.u2.std5 = nb.ech.u2.std5 + 1
  }
  
  std10 = rt(n = n, df = 10)
  test.std10.ncr = ks.test(std10,"pnorm",mean=0,sd=1)
  test.std10.u1 = ks.test(std10,"punif",-1,1)
  test.std10.u2 = ks.test(std10,"punif",-2,2)
  if (test.std10.ncr$p.value<0.05){
    nb.ech.normal.std10 = nb.ech.normal.std10 + 1
  }
  else if (test.std10.u1$p.value<0.05){
    nb.ech.u1.std10 = nb.ech.u1.std10 + 1
  }
  else if(test.std10.u2$p.value<0.05){
    nb.ech.u2.std10 = nb.ech.u2.std10 + 1
  }
}

p.ech.normal.ncr = nb.ech.normal.ncr / 400
p.ech.normal.un = nb.ech.normal.un / 400
p.ech.normal.std5 = nb.ech.normal.std5 / 400
p.ech.normal.std10 = nb.ech.normal.std10 / 400


p.ech.u1.ncr = nb.ech.u1.ncr / 400
p.ech.u1.un = nb.ech.u1.un / 400
p.ech.u1.std5 = nb.ech.u1.std5 / 400
p.ech.u1.std10 = nb.ech.u1.std10 / 400


p.ech.u2.ncr = nb.ech.u2.ncr / 400
p.ech.u2.un = nb.ech.u2.un / 400
p.ech.u2.std5 = nb.ech.u2.std5 / 400
p.ech.u2.std10 = nb.ech.u2.std10 / 400


p.ech.normal.ncr
p.ech.normal.un 
p.ech.normal.std5 
p.ech.normal.std10 

p.ech.u1.ncr
p.ech.u1.un 
p.ech.u1.std5 
p.ech.u1.std10 

p.ech.u2.ncr
p.ech.u2.un 
p.ech.u2.std5 
p.ech.u2.std10 
```

